### PR TITLE
Create affinity Python package

### PR DESCRIPTION
**Pull request by elyezer**

### CODE REVIEW

**Comment by omaciel** [comment]
Maybe `.gitignore` should only contain specific package artifacts for the project itself (e.g., anything with the word `affinity`)? I feel that it is up to the developer to have a `global` ignore file for most of the things listed here.

**Comment by elyezer** [comment]
@omaciel there is no editor specific ignore in here, those should be the items to be in the global gitigore. Those are python projects tools that may generate some of those files. This is a generic gitignore so it includes more than we need but it is better to "protect" from accidental additions. Also I think it is easy to just copy the wide spread gitignore provided by github (see https://github.com/github/gitignore/blob/master/Python.gitignore) then have to remember everything we start using a new python tool.

**Comment by omaciel** [comment]
I know there isn't any editor specific ignores, but things such as
 .Python
 build/
 develop-eggs/
 dist/
 downloads/
 eggs/
 .eggs/
 lib/
 lib64/
 parts/
 sdist/
 var/
 wheels/

are so common/expected ignores... anyhow, was just saying that one should not have to add these to a project these days, as it should be common sense and up to the developer to come up with their own global ignore list. Not a blocker, just a comment.

**Comment by elyezer** [comment]
@omaciel I agree that those are such common ignores for python project but I would rather prefer to control those here on the repo instead of assuming everyone would have those defined on their global gitignore. Thanks for the comment

**Comment by elyezer** [comment]
@psav I think this PR is on a good state for a review. Looking forward your feedback. Thank you

**Review by psav — APPROVED** [review]

**Pull request merged**
